export const kanji = {
  kage: '影',
  training: '鍛錬',
  awakening: '覚醒',
  discipline: '規律',
  evolution: '進化',
  focus: '集中',
  spirit: '魂',
  warrior: '戦士',
  shadow: '影武者',
  strength: '力',
  endurance: '忍耐',
  recovery: '回復',
  technique: '技術',
  mastery: '極意',
  lockIn: '闘魂',
  ready: '準備',
  complete: '完了',
  rank: '位',
  progress: '進歩',
  dojo: '道場',
  sensei: '先生',
  calm: '静寂',
  power: '剛力',
  heart: '心',
  body: '体',
  mind: '知',
} as const;

export const quotes = [
  '鍛錬は裏切らない',
  'Get comfortable being uncomfortable.',
  'The body achieves what the mind believes.',
  'There is no growth in the comfort zone.',
  'Discipline is the bridge between goals and accomplishment.',
  'The pain you feel today is the strength you feel tomorrow.',
  'Fall down seven times, stand up eight.',
  'Your only limit is you.',
] as const;