import { Exercise, WorkoutTemplate } from '../store/types';

export const exerciseLibrary: Exercise[] = [
  { id: 'ex1', name: 'Shadow Push', target: 'Chest', sets: 4, reps: 10, kanji: '押', category: 'push' },
  { id: 'ex2', name: 'Samurai Row', target: 'Back', sets: 4, reps: 10, kanji: '引', category: 'pull' },
  { id: 'ex3', name: 'Iron Squat', target: 'Legs', sets: 4, reps: 12, kanji: '屈', category: 'legs' },
  { id: 'ex4', name: 'Crimson Press', target: 'Shoulders', sets: 3, reps: 10, kanji: '肩', category: 'push' },
  { id: 'ex5', name: 'Steel Deadlift', target: 'Hamstrings', sets: 3, reps: 8, kanji: '腰', category: 'pull' },
  { id: 'ex6', name: 'Core Strike', target: 'Abs', sets: 3, reps: 15, kanji: '腹', category: 'core' },
  { id: 'ex7', name: 'Blade Curl', target: 'Biceps', sets: 3, reps: 12, kanji: '腕', category: 'pull' },
  { id: 'ex8', name: 'Dojo Dip', target: 'Triceps', sets: 3, reps: 12, kanji: '伸', category: 'push' },
  { id: 'ex9', name: 'Ronin Lunge', target: 'Legs', sets: 3, reps: 10, kanji: '突', category: 'legs' },
  { id: 'ex10', name: 'Warrior Pull-up', target: 'Lats', sets: 3, reps: 8, kanji: '上', category: 'pull' },
  { id: 'ex11', name: 'Dragon Fly', target: 'Lower Back', sets: 3, reps: 12, kanji: '龍', category: 'core' },
  { id: 'ex12', name: 'Temple Plank', target: 'Core', sets: 3, reps: 30, kanji: '寺', category: 'core' },
  { id: 'ex13', name: 'Silent Stretch', target: 'Hamstrings', sets: 2, reps: 30, kanji: '静', category: 'core' },
  { id: 'ex14', name: 'Storm Burpee', target: 'Full Body', sets: 5, reps: 10, kanji: '嵐', category: 'full' },
  { id: 'ex15', name: 'Rising Sun', target: 'Calves', sets: 4, reps: 20, kanji: '昇', category: 'legs' },
  { id: 'ex16', name: 'Ichiban Closer', target: 'Chest', sets: 3, reps: 10, kanji: '一', category: 'push' },
  { id: 'ex17', name: 'Hollow Hold', target: 'Abs', sets: 3, reps: 20, kanji: '空', category: 'core' },
  { id: 'ex18', name: 'Windmill', target: 'Obliques', sets: 3, reps: 12, kanji: '風', category: 'core' },
  { id: 'ex19', name: 'Fudo Stance', target: 'Glutes', sets: 3, reps: 45, kanji: '不', category: 'legs' },
  { id: 'ex20', name: 'Kensei Press', target: 'Shoulders', sets: 3, reps: 12, kanji: '剣', category: 'push' },
  { id: 'ex21', name: 'Water Flow', target: 'Back', sets: 3, reps: 12, kanji: '水', category: 'pull' },
  { id: 'ex22', name: 'Mountain Hold', target: 'Core', sets: 3, reps: 30, kanji: '山', category: 'core' },
  { id: 'ex23', name: 'Thunder Clap', target: 'Chest', sets: 4, reps: 10, kanji: '雷', category: 'push' },
  { id: 'ex24', name: 'Bamboo Reach', target: 'Lats', sets: 3, reps: 12, kanji: '竹', category: 'pull' },
  { id: 'ex25', name: 'Crane Balance', target: 'Core', sets: 3, reps: 30, kanji: '鶴', category: 'core' },
  { id: 'ex26', name: 'Fire Breath', target: 'Conditioning', sets: 4, reps: 45, kanji: '火', category: 'cardio' },
  { id: 'ex27', name: 'Iron Fist', target: 'Forearms', sets: 3, reps: 30, kanji: '拳', category: 'pull' },
  { id: 'ex28', name: 'Shadow Spar', target: 'Full Body', sets: 4, reps: 30, kanji: '影', category: 'full' },
  { id: 'ex29', name: 'Stone Wall', target: 'Chest', sets: 3, reps: 12, kanji: '石', category: 'push' },
  { id: 'ex30', name: 'Zen Reach', target: 'Shoulders', sets: 3, reps: 10, kanji: '禅', category: 'pull' },
  { id: 'ex31', name: 'Oni Slam', target: 'Full Body', sets: 4, reps: 12, kanji: '鬼', category: 'full' },
  { id: 'ex32', name: 'Serpent Twist', target: 'Obliques', sets: 3, reps: 20, kanji: '蛇', category: 'core' },
  { id: 'ex33', name: 'Phoenix Rise', target: 'Glutes', sets: 3, reps: 15, kanji: '鳳', category: 'legs' },
  { id: 'ex34', name: 'Tiger Stance', target: 'Quads', sets: 3, reps: 45, kanji: '虎', category: 'legs' },
  { id: 'ex35', name: 'Dragon Punch', target: 'Shoulders', sets: 3, reps: 15, kanji: '拳', category: 'push' },
  { id: 'ex36', name: 'Lotus Hold', target: 'Hips', sets: 2, reps: 60, kanji: '蓮', category: 'core' },
  { id: 'ex37', name: 'Wave Crash', target: 'Core', sets: 3, reps: 15, kanji: '波', category: 'core' },
  { id: 'ex38', name: 'Moon Crescent', target: 'Obliques', sets: 3, reps: 12, kanji: '月', category: 'core' },
  { id: 'ex39', name: 'Star Burst', target: 'Full Body', sets: 4, reps: 10, kanji: '星', category: 'full' },
  { id: 'ex40', name: 'Void Pull', target: 'Back', sets: 3, reps: 15, kanji: '虚', category: 'pull' },
  { id: 'ex41', name: 'Earth Push', target: 'Chest', sets: 3, reps: 15, kanji: '地', category: 'push' },
  { id: 'ex42', name: 'Heaven Press', target: 'Shoulders', sets: 3, reps: 10, kanji: '天', category: 'push' },
  { id: 'ex43', name: 'Spirit Bridge', target: 'Glutes', sets: 3, reps: 12, kanji: '霊', category: 'legs' },
  { id: 'ex44', name: 'Demon Grip', target: 'Forearms', sets: 3, reps: 30, kanji: '魔', category: 'pull' },
  { id: 'ex45', name: 'Blade Runner', target: 'Quads', sets: 4, reps: 30, kanji: '刃', category: 'legs' },
  { id: 'ex46', name: 'Night Stalker', target: 'Hamstrings', sets: 3, reps: 10, kanji: '夜', category: 'legs' },
  { id: 'ex47', name: 'Dawn Breaker', target: 'Full Body', sets: 4, reps: 8, kanji: '暁', category: 'full' },
  { id: 'ex48', name: 'Storm Caller', target: 'Back', sets: 3, reps: 10, kanji: '嵐', category: 'pull' },
  { id: 'ex49', name: 'Wind Cutter', target: 'Core', sets: 3, reps: 20, kanji: '風', category: 'core' },
  { id: 'ex50', name: 'Shadow Step', target: 'Glutes', sets: 3, reps: 10, kanji: '歩', category: 'legs' },
  { id: 'ex51', name: 'Fist of Steel', target: 'Biceps', sets: 3, reps: 12, kanji: '鋼', category: 'pull' },
  { id: 'ex52', name: 'Rising Dragon', target: 'Full Body', sets: 4, reps: 8, kanji: '昇', category: 'full' },
  { id: 'ex53', name: 'Silent Night', target: 'Core', sets: 2, reps: 60, kanji: '静', category: 'core' },
];

export const WORKOUTS = exerciseLibrary;

export const workoutTemplates: WorkoutTemplate[] = [
  {
    id: 'w1', name: 'Path of the Ronin', kanji: '浪人',
    description: 'Full body awakening for the solitary warrior', difficulty: 'beginner', duration: 30,
    exercises: [exerciseLibrary[0], exerciseLibrary[2], exerciseLibrary[6], exerciseLibrary[5]],
  },
  {
    id: 'w2', name: 'Shadow Strike', kanji: '影撃',
    description: 'Upper body power and definition', difficulty: 'intermediate', duration: 40,
    exercises: [exerciseLibrary[0], exerciseLibrary[1], exerciseLibrary[3], exerciseLibrary[7], exerciseLibrary[9]],
  },
  {
    id: 'w3', name: 'Oni Legion', kanji: '鬼軍',
    description: 'Full body intensity for seasoned warriors', difficulty: 'warrior', duration: 50,
    exercises: [exerciseLibrary[0], exerciseLibrary[4], exerciseLibrary[2], exerciseLibrary[8], exerciseLibrary[5], exerciseLibrary[9]],
  },
  {
    id: 'w4', name: 'Rising Sun', kanji: '昇陽',
    description: 'Lower body foundation builder', difficulty: 'beginner', duration: 35,
    exercises: [exerciseLibrary[2], exerciseLibrary[8], exerciseLibrary[14], exerciseLibrary[18]],
  },
  {
    id: 'w5', name: 'Dragon Path', kanji: '龍道',
    description: 'Push-focused upper body routine', difficulty: 'intermediate', duration: 40,
    exercises: [exerciseLibrary[15], exerciseLibrary[0], exerciseLibrary[3], exerciseLibrary[7], exerciseLibrary[19]],
  },
  {
    id: 'w6', name: 'Silent Night', kanji: '静夜',
    description: 'Core and recovery focused flow', difficulty: 'beginner', duration: 25,
    exercises: [exerciseLibrary[12], exerciseLibrary[24], exerciseLibrary[35]],
  },
  {
    id: 'w7', name: 'Thunder Dojo', kanji: '雷道',
    description: 'Explosive power and agility training', difficulty: 'warrior', duration: 45,
    exercises: [exerciseLibrary[22], exerciseLibrary[13], exerciseLibrary[25], exerciseLibrary[27], exerciseLibrary[46], exerciseLibrary[48]],
  },
  {
    id: 'w8', name: 'Zen Flow', kanji: '禅流',
    description: 'Mindful movement for focus and flow', difficulty: 'beginner', duration: 30,
    exercises: [exerciseLibrary[29], exerciseLibrary[12], exerciseLibrary[11], exerciseLibrary[14]],
  },
  {
    id: 'w9', name: 'Crimson Legion', kanji: '紅軍',
    description: 'Pull-focused back and arm strength', difficulty: 'intermediate', duration: 40,
    exercises: [exerciseLibrary[9], exerciseLibrary[1], exerciseLibrary[20], exerciseLibrary[6], exerciseLibrary[39]],
  },
  {
    id: 'w10', name: 'Shadow Emperor', kanji: '影帝',
    description: 'The ultimate full-body gauntlet for masters', difficulty: 'warrior', duration: 55,
    exercises: [exerciseLibrary[13], exerciseLibrary[4], exerciseLibrary[9], exerciseLibrary[30], exerciseLibrary[51], exerciseLibrary[10], exerciseLibrary[16]],
  },

  // ===== ZERO-EQUIPMENT BODYWEIGHT PROGRAMS =====
  {
    id: 'bw1', name: 'Bodyweight Ronin', kanji: '体浪',
    description: 'Zero equipment. Full body. Pure discipline.', difficulty: 'beginner', duration: 25, zeroEquipment: true,
    exercises: [exerciseLibrary[0], exerciseLibrary[2], exerciseLibrary[11], exerciseLibrary[5], exerciseLibrary[8]],
  },
  {
    id: 'bw2', name: 'Earth Warrior', kanji: '土戦',
    description: 'Ground-based strength with only your body', difficulty: 'beginner', duration: 20, zeroEquipment: true,
    exercises: [exerciseLibrary[11], exerciseLibrary[16], exerciseLibrary[28], exerciseLibrary[17], exerciseLibrary[31]],
  },
  {
    id: 'bw3', name: 'Shadow Boxing', kanji: '影拳',
    description: 'Cardio bodyweight blitz for the agile warrior', difficulty: 'intermediate', duration: 20, zeroEquipment: true,
    exercises: [exerciseLibrary[13], exerciseLibrary[27], exerciseLibrary[38], exerciseLibrary[25], exerciseLibrary[44]],
  },
  {
    id: 'bw4', name: 'Core Kata', kanji: '心型',
    description: 'Deep core conditioning with bodyweight only', difficulty: 'beginner', duration: 20, zeroEquipment: true,
    exercises: [exerciseLibrary[11], exerciseLibrary[16], exerciseLibrary[31], exerciseLibrary[35], exerciseLibrary[48]],
  },
  {
    id: 'bw5', name: 'Mountain Path', kanji: '山道',
    description: 'Full body bodyweight challenge for any space', difficulty: 'intermediate', duration: 30, zeroEquipment: true,
    exercises: [exerciseLibrary[2], exerciseLibrary[0], exerciseLibrary[21], exerciseLibrary[8], exerciseLibrary[13], exerciseLibrary[32]],
  },
  {
    id: 'bw6', name: 'No Sword, No Armor', kanji: '無刀',
    description: 'Intense zero-equipment gauntlet. Your body is your weapon.', difficulty: 'warrior', duration: 35, zeroEquipment: true,
    exercises: [exerciseLibrary[22], exerciseLibrary[30], exerciseLibrary[44], exerciseLibrary[46], exerciseLibrary[51], exerciseLibrary[27]],
  },
  {
    id: 'bw7', name: 'Floor Demon', kanji: '床鬼',
    description: 'Destroy your limits from the floor up', difficulty: 'intermediate', duration: 25, zeroEquipment: true,
    exercises: [exerciseLibrary[16], exerciseLibrary[5], exerciseLibrary[28], exerciseLibrary[17], exerciseLibrary[36], exerciseLibrary[52]],
  },
  {
    id: 'bw8', name: 'Sunrise Flow', kanji: '朝流',
    description: 'Gentle bodyweight flow to start your day', difficulty: 'beginner', duration: 15, zeroEquipment: true,
    exercises: [exerciseLibrary[12], exerciseLibrary[18], exerciseLibrary[14], exerciseLibrary[24], exerciseLibrary[29]],
  },
  {
    id: 'bw9', name: 'Stone Body', kanji: '石体',
    description: 'Isometric bodyweight holds for raw strength', difficulty: 'intermediate', duration: 20, zeroEquipment: true,
    exercises: [exerciseLibrary[11], exerciseLibrary[18], exerciseLibrary[35], exerciseLibrary[28], exerciseLibrary[21]],
  },
  {
    id: 'bw10', name: 'Air Viper', kanji: '空蛇',
    description: 'Explosive bodyweight power. No gym. No excuses.', difficulty: 'warrior', duration: 30, zeroEquipment: true,
    exercises: [exerciseLibrary[13], exerciseLibrary[38], exerciseLibrary[30], exerciseLibrary[44], exerciseLibrary[46], exerciseLibrary[25], exerciseLibrary[32]],
  },
];
